#! /bin/sh
set -e

echo "Building test archive ..."
make -C test

echo "Mirroring test archive ..."
debmirror -r "$PWD/test/debian" --method=file -d sid -a amd64 --getcontents \
    --no-check-gpg --diff=none "$AUTOPKGTEST_TMP/debian"

find "$AUTOPKGTEST_TMP/debian" -ls
cat "$AUTOPKGTEST_TMP/debian/dists/sid/Release"
