# Default config for debmirror

# The config file is a perl script so take care to follow perl syntax.
# Any setting in /etc/debmirror.conf overrides these defaults and
# ~/.debmirror.conf overrides those again. Take only what you need.
#
# The syntax is the same as on the command line and variable names
# loosely match option names. If you don't recognize something here
# then just stick to the command line.
#
# Options specified on the command line override settings in the config
# files.

# Location of the local mirror (use with care)
# $mirrordir="/path/to/mirrordir";

# Output options
$verbose=0;
$progress=0;
$debug=0;

# Download options
$host="ftp.debian.org";
$user="anonymous";
$passwd="anonymous@";
$remoteroot="debian";
$download_method="ftp";
$omit_suite_symlinks=0;
$skippackages=0;
$i18n=0;
$getcontents=0;
$do_source=1;
$max_batch=0;

# Multiple distributions, sections, arches, extras may be specified at once,
# separated by commas like in lines below.
# Uncomment the next string to mirror stretch dists.
# Otherwise, sid is the default.
# @dists="stretch,stretch-updates,stretch-backports";
@sections="main,main/debian-installer,contrib,non-free,non-free-firmware";
@arches="i386";
# If you wish to create custom CD images using for example debian-cd, you
# will probably also want mirror doc and tools.
# @rsync_extra="trace,doc,tools";
# @di_dists="dists";
# @di_archs="arches";

# Multiple includes, excludes and other options with regex arguments
# may be specified at once as a perl array.
# For example the next string excludes following sections:
# all "debug", "contrib/games", "main/sound" and all "tex" but not "text".
# @excludes_deb_section=("debug", "contrib/games", "^sound", "tex\$");

# Uncomment the next line to limit download to files with specified
# Debian Priority
# @limit_priority=("required", "important", "standard", "optional", "extra");

# Uncomment the following string to completely exclude debug symbols and
# developer files if you do not need them.
# @excludes=("-dbg_", "-dev_");
# @includes="";
# @ignores="";

# Save mirror state between runs; value sets validity of cache in days
$state_cache_days=0;

# Security/Sanity options
# @keyrings="/path/to/keyrings/file";
$ignore_release_gpg=0;
$check_gpg=1;
$ignore_missing_release=0;
$verify_checksums=0;
$ignore_small_errors=0;

# Cleanup
$pre_cleanup=0;
$post_cleanup=1;

# Locking options
$timeout=300;

# Rsync options
$rsync_batch=200;
# Uncomment next line to specify standard rsync options with
# additional transfer rate limit 5MiBs.
# $rsync_options="-aIL --partial --bwlimit=5M";

# FTP/HTTP options
$passive=0;
# $proxy="http://proxy:port/";

# Dry run
$dry_run=0;

# Don't keep diff files but use them
$diff_mode="use";

# The config file must return true or perl complains.
# Always copy this.
1;
